apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-24
  namespace: namespace-1
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        team: cs
      annotations:
        env: staging
        on-call-priority: one
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
