apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: namespace-1
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: my-sa-namespace-1
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
